# Generated by Django 4.0.5 on 2022-06-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_trackerAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cieduser',
            name='email',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
