# Generated by Django 4.0.5 on 2022-06-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_trackerAPP', '0002_alter_cieduser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cieduser',
            name='username',
        ),
    ]
