# Generated by Django 4.0.5 on 2022-06-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_trackerAPP', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=100)),
                ('currency_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_amount', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_trackerAPP.currency')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_trackerAPP.category')),
            ],
        ),
    ]
