# Generated by Django 4.0.5 on 2022-06-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_trackerAPP', '0005_currency_daily_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
